<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Alumno extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Alumno_model');
    } 

    /*
     * Listing of alumnos
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('alumno/index?');
        $config['total_rows'] = $this->Alumno_model->get_all_alumnos_count();
        $this->pagination->initialize($config);

        $data['alumnos'] = $this->Alumno_model->get_all_alumnos($params);
        
        $data['_view'] = 'alumnos/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new alumno
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_carrera' => $this->input->post('id_carrera'),
				'id_curso' => $this->input->post('id_curso'),
				'id_estado_usuario' => $this->input->post('id_estado_usuario'),
				'id_datos_personales' => $this->input->post('id_datos_personales'),
            );
            
            $alumno_id = $this->Alumno_model->add_alumno($params);
            redirect('alumno/index');
        }
        else
        {
			$this->load->model('Carrera_model');
			$data['all_carreras'] = $this->Carrera_model->get_all_carreras();

			$this->load->model('Curso_model');
			$data['all_cursos'] = $this->Curso_model->get_all_cursos();

			$this->load->model('Estado_usuario_model');
			$data['all_estados_usuario'] = $this->Estado_usuario_model->get_all_estados_usuario();

			$this->load->model('Datos_personales_model');
			$data['all_datos_personales'] = $this->Datos_personales_model->get_all_datos_personales();
            
            $data['_view'] = 'alumnos/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a alumno
     */
    function edit($id_alumnos)
    {   
        // check if the alumno exists before trying to edit it
        $data['alumno'] = $this->Alumno_model->get_alumno($id_alumnos);
        
        if(isset($data['alumno']['id_alumnos']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_carrera' => $this->input->post('id_carrera'),
					'id_curso' => $this->input->post('id_curso'),
					'id_estado_usuario' => $this->input->post('id_estado_usuario'),
					'id_datos_personales' => $this->input->post('id_datos_personales'),
                );

                $this->Alumno_model->update_alumno($id_alumnos,$params);            
                redirect('alumno/index');
            }
            else
            {
				$this->load->model('Carrera_model');
				$data['all_carreras'] = $this->Carrera_model->get_all_carreras();

				$this->load->model('Curso_model');
				$data['all_cursos'] = $this->Curso_model->get_all_cursos();

				$this->load->model('Estado_usuario_model');
				$data['all_estados_usuario'] = $this->Estado_usuario_model->get_all_estados_usuario();

				$this->load->model('Datos_personales_model');
				$data['all_datos_personales'] = $this->Datos_personales_model->get_all_datos_personales();

                $data['_view'] = 'alumnos/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The alumno you are trying to edit does not exist.');
    } 

    /*
     * Deleting alumno
     */
    function remove($id_alumnos)
    {
        $alumno = $this->Alumno_model->get_alumno($id_alumnos);

        // check if the alumno exists before trying to delete it
        if(isset($alumno['id_alumnos']))
        {
            $this->Alumno_model->delete_alumno($id_alumnos);
            redirect('alumno/index');
        }
        else
            show_error('The alumno you are trying to delete does not exist.');
    }
    
}
