<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Condicion_ventum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Condicion_ventum_model');
    } 

    /*
     * Listing of condicion_venta
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('condicion_ventum/index?');
        $config['total_rows'] = $this->Condicion_ventum_model->get_all_condicion_venta_count();
        $this->pagination->initialize($config);

        $data['condicion_venta'] = $this->Condicion_ventum_model->get_all_condicion_venta($params);
        
        $data['_view'] = 'condicion_ventum/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new condicion_ventum
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('descripcion','Descripcion','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'descripcion' => $this->input->post('descripcion'),
            );
            
            $condicion_ventum_id = $this->Condicion_ventum_model->add_condicion_ventum($params);
            redirect('condicion_ventum/index');
        }
        else
        {            
            $data['_view'] = 'condicion_ventum/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a condicion_ventum
     */
    function edit($id_cond_venta)
    {   
        // check if the condicion_ventum exists before trying to edit it
        $data['condicion_ventum'] = $this->Condicion_ventum_model->get_condicion_ventum($id_cond_venta);
        
        if(isset($data['condicion_ventum']['id_cond_venta']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('descripcion','Descripcion','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'descripcion' => $this->input->post('descripcion'),
                );

                $this->Condicion_ventum_model->update_condicion_ventum($id_cond_venta,$params);            
                redirect('condicion_ventum/index');
            }
            else
            {
                $data['_view'] = 'condicion_ventum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The condicion_ventum you are trying to edit does not exist.');
    } 

    /*
     * Deleting condicion_ventum
     */
    function remove($id_cond_venta)
    {
        $condicion_ventum = $this->Condicion_ventum_model->get_condicion_ventum($id_cond_venta);

        // check if the condicion_ventum exists before trying to delete it
        if(isset($condicion_ventum['id_cond_venta']))
        {
            $this->Condicion_ventum_model->delete_condicion_ventum($id_cond_venta);
            redirect('condicion_ventum/index');
        }
        else
            show_error('The condicion_ventum you are trying to delete does not exist.');
    }
    
}
