<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Curso extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Curso_model');
    } 

    /*
     * Listing of cursos
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('curso/index?');
        $config['total_rows'] = $this->Curso_model->get_all_cursos_count();
        $this->pagination->initialize($config);

        $data['cursos'] = $this->Curso_model->get_all_cursos($params);
        
        $data['_view'] = 'curso/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new curso
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('curso_estado','Curso Estado','required');
		$this->form_validation->set_rules('id_profesor','Id Profesor','required');
		$this->form_validation->set_rules('descripcion','Descripcion','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'curso_estado' => $this->input->post('curso_estado'),
				'id_profesor' => $this->input->post('id_profesor'),
				'descripcion' => $this->input->post('descripcion'),
            );
            
            $curso_id = $this->Curso_model->add_curso($params);
            redirect('curso/index');
        }
        else
        {
			$this->load->model('Profesores_model');
			$data['all_profesores'] = $this->Profesores_model->get_all_profesores();
            
            $data['_view'] = 'curso/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a curso
     */
    function edit($id_cursos)
    {   
        // check if the curso exists before trying to edit it
        $data['curso'] = $this->Curso_model->get_curso($id_cursos);
        
        if(isset($data['curso']['id_cursos']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('curso_estado','Curso Estado','required');
			$this->form_validation->set_rules('id_profesor','Id Profesor','required');
			$this->form_validation->set_rules('descripcion','Descripcion','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'curso_estado' => $this->input->post('curso_estado'),
					'id_profesor' => $this->input->post('id_profesor'),
					'descripcion' => $this->input->post('descripcion'),
                );

                $this->Curso_model->update_curso($id_cursos,$params);            
                redirect('curso/index');
            }
            else
            {
				$this->load->model('Profesores_model');
				$data['all_profesores'] = $this->Profesores_model->get_all_profesores();

                $data['_view'] = 'curso/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The curso you are trying to edit does not exist.');
    } 

    /*
     * Deleting curso
     */
    function remove($id_cursos)
    {
        $curso = $this->Curso_model->get_curso($id_cursos);

        // check if the curso exists before trying to delete it
        if(isset($curso['id_cursos']))
        {
            $this->Curso_model->delete_curso($id_cursos);
            redirect('curso/index');
        }
        else
            show_error('The curso you are trying to delete does not exist.');
    }
    
}
