<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estado_usuario extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Estado_usuario_model');
    } 

    /*
     * Listing of estados_usuario
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('estado_usuario/index?');
        $config['total_rows'] = $this->Estado_usuario_model->get_all_estados_usuario_count();
        $this->pagination->initialize($config);

        $data['estados_usuario'] = $this->Estado_usuario_model->get_all_estados_usuario($params);
        
        $data['_view'] = 'estados_usuario/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new estado_usuario
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'descripcion' => $this->input->post('descripcion'),
            );
            
            $estado_usuario_id = $this->Estado_usuario_model->add_estado_usuario($params);
            redirect('estado_usuario/index');
        }
        else
        {            
            $data['_view'] = 'estados_usuario/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a estado_usuario
     */
    function edit($id_estado_usuario)
    {   
        // check if the estado_usuario exists before trying to edit it
        $data['estado_usuario'] = $this->Estado_usuario_model->get_estado_usuario($id_estado_usuario);
        
        if(isset($data['estado_usuario']['id_estado_usuario']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descripcion' => $this->input->post('descripcion'),
                );

                $this->Estado_usuario_model->update_estado_usuario($id_estado_usuario,$params);            
                redirect('estado_usuario/index');
            }
            else
            {
                $data['_view'] = 'estados_usuario/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The estado_usuario you are trying to edit does not exist.');
    } 

    /*
     * Deleting estado_usuario
     */
    function remove($id_estado_usuario)
    {
        $estado_usuario = $this->Estado_usuario_model->get_estado_usuario($id_estado_usuario);

        // check if the estado_usuario exists before trying to delete it
        if(isset($estado_usuario['id_estado_usuario']))
        {
            $this->Estado_usuario_model->delete_estado_usuario($id_estado_usuario);
            redirect('estado_usuario/index');
        }
        else
            show_error('The estado_usuario you are trying to delete does not exist.');
    }
    
}
