<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Profesores extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Profesores_model');
    } 

    /*
     * Listing of profesores
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('profesor/index?');
        $config['total_rows'] = $this->Profesores_model->get_all_profesores_count();
        $this->pagination->initialize($config);

        $data['profesores'] = $this->Profesores_model->get_all_profesores($params);
        
        $data['_view'] = 'profesor/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new profesor
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('profesor_estado','Profesor Estado','required');
		$this->form_validation->set_rules('id_localidad','Id Localidad','required');
		$this->form_validation->set_rules('nombre','Nombre','required|alpha');
		$this->form_validation->set_rules('apellido','Apellido','required|alpha');
		$this->form_validation->set_rules('edad','Edad','integer|less_than[120]');
		$this->form_validation->set_rules('dni','Dni','required|max_length[8]');
		$this->form_validation->set_rules('domicilio','Domicilio','required');
		$this->form_validation->set_rules('estudios','Estudios','required|alpha');
		$this->form_validation->set_rules('email','Email','required|valid_email');
		$this->form_validation->set_rules('telefono','Telefono','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'profesor_estado' => $this->input->post('profesor_estado'),
				'id_localidad' => $this->input->post('id_localidad'),
				'nombre' => $this->input->post('nombre'),
				'apellido' => $this->input->post('apellido'),
				'edad' => $this->input->post('edad'),
				'dni' => $this->input->post('dni'),
				'domicilio' => $this->input->post('domicilio'),
				'estudios' => $this->input->post('estudios'),
				'email' => $this->input->post('email'),
				'telefono' => $this->input->post('telefono'),
            );
            
            $profesor_id = $this->Profesores_model->add_profesor($params);
            redirect('profesores/index');
        }
        else
        {
			$this->load->model('Localidades_model');
			$data['all_localidades'] = $this->Localidades_model->get_all_localidades();
            
            $data['_view'] = 'profesor/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a profesor
     */
    function edit($id_profesores)
    {   
        // check if the profesor exists before trying to edit it
        $data['profesor'] = $this->Profesores_model->get_profesor($id_profesores);
        
        if(isset($data['profesor']['id_profesores']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('profesor_estado','Profesor Estado','required');
			$this->form_validation->set_rules('id_localidad','Id Localidad','required');
			$this->form_validation->set_rules('nombre','Nombre','required|alpha');
			$this->form_validation->set_rules('apellido','Apellido','required|alpha');
			$this->form_validation->set_rules('edad','Edad','integer|less_than[120]');
			$this->form_validation->set_rules('dni','Dni','required|max_length[8]');
			$this->form_validation->set_rules('domicilio','Domicilio','required');
			$this->form_validation->set_rules('estudios','Estudios','required|alpha');
			$this->form_validation->set_rules('email','Email','required|valid_email');
			$this->form_validation->set_rules('telefono','Telefono','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'profesor_estado' => $this->input->post('profesor_estado'),
					'id_localidad' => $this->input->post('id_localidad'),
					'nombre' => $this->input->post('nombre'),
					'apellido' => $this->input->post('apellido'),
					'edad' => $this->input->post('edad'),
					'dni' => $this->input->post('dni'),
					'domicilio' => $this->input->post('domicilio'),
					'estudios' => $this->input->post('estudios'),
					'email' => $this->input->post('email'),
					'telefono' => $this->input->post('telefono'),
                );

                $this->Profesores_model->update_profesor($id_profesores,$params);            
                redirect('profesores/index');
            }
            else
            {
				$this->load->model('Localidades_model');
				$data['all_localidades'] = $this->Localidades_model->get_all_localidades();

                $data['_view'] = 'profesor/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The profesor you are trying to edit does not exist.');
    } 

    /*
     * Deleting profesor
     */
    function remove($id_profesores)
    {
        $profesor = $this->Profesores_model->get_profesor($id_profesores);

        // check if the profesor exists before trying to delete it
        if(isset($profesor['id_profesores']))
        {
            $this->Profesores_model->delete_profesor($id_profesores);
            redirect('profesores/index');
        }
        else
            show_error('The profesor you are trying to delete does not exist.');
    }
    
}
