<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Provincia extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Provincia_model');
    } 

    /*
     * Listing of provincias
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('provincia/index?');
        $config['total_rows'] = $this->Provincia_model->get_all_provincias_count();
        $this->pagination->initialize($config);

        $data['provincias'] = $this->Provincia_model->get_all_provincias($params);
        
        $data['_view'] = 'provincias/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new provincia
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'descripcion' => $this->input->post('descripcion'),
            );
            
            $provincia_id = $this->Provincia_model->add_provincia($params);
            redirect('provincia/index');
        }
        else
        {            
            $data['_view'] = 'provincias/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a provincia
     */
    function edit($id_provincia)
    {   
        // check if the provincia exists before trying to edit it
        $data['provincia'] = $this->Provincia_model->get_provincia($id_provincia);
        
        if(isset($data['provincia']['id_provincia']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descripcion' => $this->input->post('descripcion'),
                );

                $this->Provincia_model->update_provincia($id_provincia,$params);            
                redirect('provincia/index');
            }
            else
            {
                $data['_view'] = 'provincias/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The provincia you are trying to edit does not exist.');
    } 

    /*
     * Deleting provincia
     */
    function remove($id_provincia)
    {
        $provincia = $this->Provincia_model->get_provincia($id_provincia);

        // check if the provincia exists before trying to delete it
        if(isset($provincia['id_provincia']))
        {
            $this->Provincia_model->delete_provincia($id_provincia);
            redirect('provincia/index');
        }
        else
            show_error('The provincia you are trying to delete does not exist.');
    }
    
}
