<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_usuario extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_usuario_model');
    } 

    /*
     * Listing of tipo_usuarios
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tipo_usuario/index?');
        $config['total_rows'] = $this->Tipo_usuario_model->get_all_tipo_usuarios_count();
        $this->pagination->initialize($config);

        $data['tipo_usuarios'] = $this->Tipo_usuario_model->get_all_tipo_usuarios($params);
        
        $data['_view'] = 'tipo_usuarios/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tipo_usuario
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'descripcion' => $this->input->post('descripcion'),
            );
            
            $tipo_usuario_id = $this->Tipo_usuario_model->add_tipo_usuario($params);
            redirect('tipo_usuario/index');
        }
        else
        {            
            $data['_view'] = 'tipo_usuarios/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tipo_usuario
     */
    function edit($id_tipo_usuario)
    {   
        // check if the tipo_usuario exists before trying to edit it
        $data['tipo_usuario'] = $this->Tipo_usuario_model->get_tipo_usuario($id_tipo_usuario);
        
        if(isset($data['tipo_usuario']['id_tipo_usuario']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descripcion' => $this->input->post('descripcion'),
                );

                $this->Tipo_usuario_model->update_tipo_usuario($id_tipo_usuario,$params);            
                redirect('tipo_usuario/index');
            }
            else
            {
                $data['_view'] = 'tipo_usuarios/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipo_usuario you are trying to edit does not exist.');
    } 

    /*
     * Deleting tipo_usuario
     */
    function remove($id_tipo_usuario)
    {
        $tipo_usuario = $this->Tipo_usuario_model->get_tipo_usuario($id_tipo_usuario);

        // check if the tipo_usuario exists before trying to delete it
        if(isset($tipo_usuario['id_tipo_usuario']))
        {
            $this->Tipo_usuario_model->delete_tipo_usuario($id_tipo_usuario);
            redirect('tipo_usuario/index');
        }
        else
            show_error('The tipo_usuario you are trying to delete does not exist.');
    }
    
}
