<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usuario extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Usuario_model');
    } 

    /*
     * Listing of usuarios
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('usuario/index?');
        $config['total_rows'] = $this->Usuario_model->get_all_usuarios_count();
        $this->pagination->initialize($config);

        $data['usuarios'] = $this->Usuario_model->get_all_usuarios($params);
        
        $data['_view'] = 'usuarios/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new usuario
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('password','Password','required|min_length[6]|alpha_numeric');
		$this->form_validation->set_rules('nombre','Nombre','required|min_length[6]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_tipo_usuario' => $this->input->post('id_tipo_usuario'),
				'id_estado_usuario' => $this->input->post('id_estado_usuario'),
				'password' => $this->input->post('password'),
				'nombre' => $this->input->post('nombre'),
            );
            
            $usuario_id = $this->Usuario_model->add_usuario($params);
            redirect('usuario/index');
        }
        else
        {
			$this->load->model('Tipo_usuario_model');
			$data['all_tipo_usuarios'] = $this->Tipo_usuario_model->get_all_tipo_usuarios();

			$this->load->model('Estado_usuario_model');
			$data['all_estados_usuario'] = $this->Estado_usuario_model->get_all_estados_usuario();
            
            $data['_view'] = 'usuarios/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a usuario
     */
    function edit($id_usuario)
    {   
        // check if the usuario exists before trying to edit it
        $data['usuario'] = $this->Usuario_model->get_usuario($id_usuario);
        
        if(isset($data['usuario']['id_usuario']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('password','Password','required|min_length[6]|alpha_numeric');
			$this->form_validation->set_rules('nombre','Nombre','required|min_length[6]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_tipo_usuario' => $this->input->post('id_tipo_usuario'),
					'id_estado_usuario' => $this->input->post('id_estado_usuario'),
					'password' => $this->input->post('password'),
					'nombre' => $this->input->post('nombre'),
                );

                $this->Usuario_model->update_usuario($id_usuario,$params);            
                redirect('usuario/index');
            }
            else
            {
				$this->load->model('Tipo_usuario_model');
				$data['all_tipo_usuarios'] = $this->Tipo_usuario_model->get_all_tipo_usuarios();

				$this->load->model('Estado_usuario_model');
				$data['all_estados_usuario'] = $this->Estado_usuario_model->get_all_estados_usuario();

                $data['_view'] = 'usuarios/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The usuario you are trying to edit does not exist.');
    } 

    /*
     * Deleting usuario
     */
    function remove($id_usuario)
    {
        $usuario = $this->Usuario_model->get_usuario($id_usuario);

        // check if the usuario exists before trying to delete it
        if(isset($usuario['id_usuario']))
        {
            $this->Usuario_model->delete_usuario($id_usuario);
            redirect('usuario/index');
        }
        else
            show_error('The usuario you are trying to delete does not exist.');
    }
    
}
