<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usuario extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Usuario_model');
    } 

    /*
     * Listing of usuarios
     */
    function index()
    {
        $data['usuarios'] = $this->Usuario_model->get_all_usuarios();
        
        $data['_view'] = 'usuario/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new usuario
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'usuario_estado' => $this->input->post('usuario_estado'),
				'id_tipo_usuario' => $this->input->post('id_tipo_usuario'),
				'password' => $this->input->post('password'),
				'nombre' => $this->input->post('nombre'),
            );
            
            $usuario_id = $this->Usuario_model->add_usuario($params);
            redirect('usuario/index');
        }
        else
        {
			$this->load->model('Tipo_usuario_model');
			$data['all_tipo_usuario'] = $this->Tipo_usuario_model->get_all_tipo_usuario();
            
            $data['_view'] = 'usuario/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a usuario
     */
    function edit($id_usuario)
    {   
        // check if the usuario exists before trying to edit it
        $data['usuario'] = $this->Usuario_model->get_usuario($id_usuario);
        
        if(isset($data['usuario']['id_usuario']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'usuario_estado' => $this->input->post('usuario_estado'),
					'id_tipo_usuario' => $this->input->post('id_tipo_usuario'),
					'password' => $this->input->post('password'),
					'nombre' => $this->input->post('nombre'),
                );

                $this->Usuario_model->update_usuario($id_usuario,$params);            
                redirect('usuario/index');
            }
            else
            {
				$this->load->model('Tipo_usuario_model');
				$data['all_tipo_usuario'] = $this->Tipo_usuario_model->get_all_tipo_usuario();

                $data['_view'] = 'usuario/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The usuario you are trying to edit does not exist.');
    } 

    /*
     * Deleting usuario
     */
    function remove($id_usuario)
    {
        $usuario = $this->Usuario_model->get_usuario($id_usuario);

        // check if the usuario exists before trying to delete it
        if(isset($usuario['id_usuario']))
        {
            $this->Usuario_model->delete_usuario($id_usuario);
            redirect('usuario/index');
        }
        else
            show_error('The usuario you are trying to delete does not exist.');
    }
    
}
