<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Venta extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Venta_model');
    } 

    /*
     * Listing of ventas
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('venta/index?');
        $config['total_rows'] = $this->Venta_model->get_all_ventas_count();
        $this->pagination->initialize($config);

        $data['ventas'] = $this->Venta_model->get_all_ventas($params);
        
        $data['_view'] = 'venta/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new venta
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_condicion_venta' => $this->input->post('id_condicion_venta'),
				'id_cond_iva' => $this->input->post('id_cond_iva'),
				'id_domicilio_comercial' => $this->input->post('id_domicilio_comercial'),
				'fecha_operacion' => $this->input->post('fecha_operacion'),
				'tipo_doc' => $this->input->post('tipo_doc'),
				'num_documento' => $this->input->post('num_documento'),
				'razon_soc' => $this->input->post('razon_soc'),
				'email' => $this->input->post('email'),
				'prod_servicio' => $this->input->post('prod_servicio'),
				'precio_unitario' => $this->input->post('precio_unitario'),
            );
            
            $venta_id = $this->Venta_model->add_venta($params);
            redirect('venta/index');
        }
        else
        {
			$this->load->model('Condicion_venta_model');
			$data['all_condiciones_venta'] = $this->Condicion_venta_model->get_all_condiciones_venta();

			$this->load->model('Condicion_iva_model');
			$data['all_condiciones_iva'] = $this->Condicion_iva_model->get_all_condiciones_iva();

			$this->load->model('Domicilio_comercial_model');
			$data['all_domicilios_comerciales'] = $this->Domicilio_comercial_model->get_all_domicilios_comerciales();
            
            $data['_view'] = 'venta/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a venta
     */
    function edit($id_ventas)
    {   
        // check if the venta exists before trying to edit it
        $data['venta'] = $this->Venta_model->get_venta($id_ventas);
        
        if(isset($data['venta']['id_ventas']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_condicion_venta' => $this->input->post('id_condicion_venta'),
					'id_cond_iva' => $this->input->post('id_cond_iva'),
					'id_domicilio_comercial' => $this->input->post('id_domicilio_comercial'),
					'fecha_operacion' => $this->input->post('fecha_operacion'),
					'tipo_doc' => $this->input->post('tipo_doc'),
					'num_documento' => $this->input->post('num_documento'),
					'razon_soc' => $this->input->post('razon_soc'),
					'email' => $this->input->post('email'),
					'prod_servicio' => $this->input->post('prod_servicio'),
					'precio_unitario' => $this->input->post('precio_unitario'),
                );

                $this->Venta_model->update_venta($id_ventas,$params);            
                redirect('venta/index');
            }
            else
            {
				$this->load->model('Condicion_venta_model');
				$data['all_condiciones_venta'] = $this->Condicion_venta_model->get_all_condiciones_venta();

				$this->load->model('Condicion_iva_model');
				$data['all_condiciones_iva'] = $this->Condicion_iva_model->get_all_condiciones_iva();

				$this->load->model('Domicilio_comercial_model');
				$data['all_domicilios_comerciales'] = $this->Domicilio_comercial_model->get_all_domicilios_comerciales();

                $data['_view'] = 'venta/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The venta you are trying to edit does not exist.');
    } 

    /*
     * Deleting venta
     */
    function remove($id_ventas)
    {
        $venta = $this->Venta_model->get_venta($id_ventas);

        // check if the venta exists before trying to delete it
        if(isset($venta['id_ventas']))
        {
            $this->Venta_model->delete_venta($id_ventas);
            redirect('venta/index');
        }
        else
            show_error('The venta you are trying to delete does not exist.');
    }
    
}
