<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Alumno_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get alumno by id_alumnos
     */
    function get_alumno($id_alumnos)
    {
        return $this->db->get_where('alumnos',array('id_alumnos'=>$id_alumnos))->row_array();
    }
    
    /*
     * Get all alumnos count
     */
    function get_all_alumnos_count()
    {
        $this->db->from('alumnos');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all alumnos
     */
    function get_all_alumnos($params = array())
    {
        $this->db->order_by('id_alumnos', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('alumnos')->result_array();
    }
        
    /*
     * function to add new alumno
     */
    function add_alumno($params)
    {
        $this->db->insert('alumnos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update alumno
     */
    function update_alumno($id_alumnos,$params)
    {
        $this->db->where('id_alumnos',$id_alumnos);
        return $this->db->update('alumnos',$params);
    }
    
    /*
     * function to delete alumno
     */
    function delete_alumno($id_alumnos)
    {
        return $this->db->delete('alumnos',array('id_alumnos'=>$id_alumnos));
    }
}
