<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Curso_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get curso by id_cursos
     */
    function get_curso($id_cursos)
    {
        return $this->db->get_where('cursos',array('id_cursos'=>$id_cursos))->row_array();
    }
    
    /*
     * Get all cursos count
     */
    function get_all_cursos_count()
    {
        $this->db->from('cursos');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all cursos
     */
    function get_all_cursos($params = array())
    {
        $this->db->order_by('id_cursos', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('cursos')->result_array();
    }
        
    /*
     * function to add new curso
     */
    function add_curso($params)
    {
        $this->db->insert('cursos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update curso
     */
    function update_curso($id_cursos,$params)
    {
        $this->db->where('id_cursos',$id_cursos);
        return $this->db->update('cursos',$params);
    }
    
    /*
     * function to delete curso
     */
    function delete_curso($id_cursos)
    {
        return $this->db->delete('cursos',array('id_cursos'=>$id_cursos));
    }
}
