<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Domicilio_comercial_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get domicilio_comercial by id_domicilio_comer
     */
    function get_domicilio_comercial($id_domicilio_comer)
    {
        return $this->db->get_where('domicilio_comercial',array('id_domicilio_comer'=>$id_domicilio_comer))->row_array();
    }
    
    /*
     * Get all domicilio_comercial count
     */
    function get_all_domicilio_comercial_count()
    {
        $this->db->from('domicilio_comercial');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all domicilio_comercial
     */
    function get_all_domicilio_comercial($params = array())
    {
        $this->db->order_by('id_domicilio_comer', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('domicilio_comercial')->result_array();
    }
        
    /*
     * function to add new domicilio_comercial
     */
    function add_domicilio_comercial($params)
    {
        $this->db->insert('domicilio_comercial',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update domicilio_comercial
     */
    function update_domicilio_comercial($id_domicilio_comer,$params)
    {
        $this->db->where('id_domicilio_comer',$id_domicilio_comer);
        return $this->db->update('domicilio_comercial',$params);
    }
    
    /*
     * function to delete domicilio_comercial
     */
    function delete_domicilio_comercial($id_domicilio_comer)
    {
        return $this->db->delete('domicilio_comercial',array('id_domicilio_comer'=>$id_domicilio_comer));
    }
}
