<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Group_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get group by id
     */
    function get_group($id)
    {
        return $this->db->get_where('groups',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all groups count
     */
    function get_all_groups_count()
    {
        $this->db->from('groups');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all groups
     */
    function get_all_groups($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('groups')->result_array();
    }
        
    /*
     * function to add new group
     */
    function add_group($params)
    {
        $this->db->insert('groups',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update group
     */
    function update_group($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('groups',$params);
    }
    
    /*
     * function to delete group
     */
    function delete_group($id)
    {
        return $this->db->delete('groups',array('id'=>$id));
    }
}
