<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Login_attempt_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get login_attempt by id
     */
    function get_login_attempt($id)
    {
        return $this->db->get_where('login_attempts',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all login_attempts count
     */
    function get_all_login_attempts_count()
    {
        $this->db->from('login_attempts');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all login_attempts
     */
    function get_all_login_attempts($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('login_attempts')->result_array();
    }
        
    /*
     * function to add new login_attempt
     */
    function add_login_attempt($params)
    {
        $this->db->insert('login_attempts',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update login_attempt
     */
    function update_login_attempt($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('login_attempts',$params);
    }
    
    /*
     * function to delete login_attempt
     */
    function delete_login_attempt($id)
    {
        return $this->db->delete('login_attempts',array('id'=>$id));
    }
}
