<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Venta_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get venta by id_ventas
     */
    function get_venta($id_ventas)
    {
        return $this->db->get_where('ventas',array('id_ventas'=>$id_ventas))->row_array();
    }
    
    /*
     * Get all ventas count
     */
    function get_all_ventas_count()
    {
        $this->db->from('ventas');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all ventas
     */
    function get_all_ventas($params = array())
    {
        $this->db->order_by('id_ventas', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('ventas')->result_array();
    }
        
    /*
     * function to add new venta
     */
    function add_venta($params)
    {
        $this->db->insert('ventas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update venta
     */
    function update_venta($id_ventas,$params)
    {
        $this->db->where('id_ventas',$id_ventas);
        return $this->db->update('ventas',$params);
    }
    
    /*
     * function to delete venta
     */
    function delete_venta($id_ventas)
    {
        return $this->db->delete('ventas',array('id_ventas'=>$id_ventas));
    }
}
